### ISSUE TITLE
thiết kế cơ sở dữ liệu

### ISSUE THREAD

**Issue by frkami123** [laravel-noobs/NEWS#2]

**Comment by leminhquocbt** [comment]
![Sơ đồ cơ sở dữ liệu](https://www.dropbox.com/s/6cj0pjfkxwxocxg/11218908_1714719065428125_245709880027544744_n.jpg?dl=1)

**Comment by leminhquocbt** [comment]
![Lược đồ cơ sở dữ liệu](https://www.dropbox.com/s/pvb7ky2g7zk5d1f/12316674_1714639872102711_275633347474610618_n.jpg?dl=1)

**Comment by frkami123** [comment]
làm thế thì biết comment của user nào?

+ Respond xem khóa đã đúng là khóa chưa hay vẫn là siêu khóa?

+ IDPosts IDComment là siêu khóa hay là khóa?

+ bài viết vầy sao biết duyệt hay chưa? biết của user nào viết?

+ IDTag bỏ vào trong post để làm gì? một bài viết chỉ có một tag à?

+ làm vầy sao biết lượt view của bài viết?

+ bài viết được viết ngày nào? chỉnh sửa lần cuối lúc nào?

lưu ý thiết kế cho MySQL server:
tên bảng, cột chỉ dùng chữ thường và gạch dưới.
tên bảng không dùng số nhiều nhé. post, category
gọi là role, chứ ko gọi là position. gọi là feedback chứ không gọi là respond.

nhìn chung quan hệ của Tag với Post mấy ông làm đúng, quan hệ giữa Position với User làm đúng. Xác định được thực thể. Nhiêu đây thực thể là gần đủ rồi. Thiếu cái thực thể trạng thái của bài viết nữa

Xem lại quan hệ giữa Comment với Post và quan hệ Comment với User. 
Xem lại quan hệ giữa Category với chính nó.
Xem lại Quan hệ giữa Post và User
Xem lại quan hệ giữa User và Respond

Coi lại mấy cái khóa coi đúng chưa? phân biệt khóa với siêu khóa đi.

**Comment by leminhquocbt** [comment]
![Lược đồ cơ sở dữ liệu 2](https://www.dropbox.com/s/6cj0pjfkxwxocxg/11218908_1714719065428125_245709880027544744_n.jpg?dl=1)

**Comment by frkami123** [comment]
Comment dùng siêu khóa làm khóa, Respond dùng siêu khóa làm khóa.
Category chưa đệ quy thì sao làm được category con
User sao lại có 2 cái khóa ngoại tham chiếu tới Postsition?

nhìn chung mấy ông bắt đầu hiểu rồi đó bước đầu xác định đúng thực thể, hiểu đc quan hệ cha con, quan hệ nhiều nhiều. theo tui thấy vậy là tương đối ổn lúc đầu. tuy nhiên mấy ông chưa bao quát hết dữ liệu (thiếu các cột), chưa có nhận ra quan hệ đệ quy cha con, xác định khóa chưa tốt.

**Comment by frkami123** [comment]
![Lược đồ cơ sở dữ liệu](https://www.dropbox.com/s/34zlrx4ln8rdgii/12274744_488431897994891_7880705385059136309_n.jpg?dl=1)

**Comment by frkami123** [comment]
thêm created_at, updated_at vào bảng user nha.
thêm description vào bảng category

**Comment by frkami123** [comment]
user_id ở bảng feedback có thể null vì khách vãng lai cũng có thể phản hồi.

**Comment by frkami123** [comment]
- bảng user cần sửa tên thuộc tính username thành name và phải là duy nhất (unique)
- bảng user cần sửa độ dài thuộc tính password thành 60
- cần thêm bảng password_resets có
+ thuộc tính dạng chuỗi email (tương tự bảng user)
+ thuộc tính dạng chuỗi token
+ thuộc tính dạng timestamp là created_at
https://github.com/laravel-noobs/NEWS/issues/34

ngoài ra nên đôi published_at thành datetime đễ rõ hơn, timestamp là không phù hợp.

**Comment by leminhquocbt** [comment]
![DataBase hoàn chỉnh]
(https://www.dropbox.com/s/geop1l8e43h1mgy/database_NEWS.png?dl=1)

**Comment by frkami123** [comment]
ông làm xong thì upload file thiết kế lên đây luôn. dùng chức năng export của toad để export ra đẹp hơn. để PNG scale tầm 150~200 là được.

**Comment by leminhquocbt** [comment]
![Database NEWS hoàn chỉnh nhé]
(https://www.dropbox.com/s/6ic6ttook3dwjty/Untitled.png?dl=1)

**Comment by leminhquocbt** [comment]
![Database NEWS hoàn chỉnh](https://www.dropbox.com/s/6ic6ttook3dwjty/Untitled.png?dl=1)

**Comment by frkami123** [comment]
update-at sai rồi kìa

updated_at

**Comment by leminhquocbt** [comment]
![Đã Fix](https://www.dropbox.com/s/6ic6ttook3dwjty/Untitled.png?dl=1)

**Comment by leminhquocbt** [comment]
fix rồi nha

**Comment by leminhquocbt** [comment]
https://www.dropbox.com/s/6ic6ttook3dwjty/Untitled.png?dl=1
File CSDL nha

**Comment by frkami123** [comment]
cái này file hình mà, có phải file thiết kế đâu.

**Comment by leminhquocbt** [comment]
https://www.dropbox.com/s/9lrcwbhlfz75569/MySQL%205_6.txp?dl=1
File CSDL nha

**Comment by frkami123** [comment]
khóa của post_status là tinyint nhưng đổi lại thành smallint

**Comment by frkami123** [comment]
slug sao không có unique. =.= làm ăn gì kỳ cụ vậy Quốc?

**Comment by leminhquocbt** [comment]
https://www.dropbox.com/s/9lrcwbhlfz75569/MySQL%205_6.txp?dl=1
File CSDL fix hết rồi nha

**Comment by frkami123** [comment]
uhm nhìn sơ là được rồi, export cái hình ra đi post vào đây rồi close issue lại. tắt luôn dissus.

**Comment by leminhquocbt** [comment]
![Fixed](https://www.dropbox.com/s/6ic6ttook3dwjty/Untitled.png?dl=1)

**Comment by frkami123** [comment]
id của post là smallint ? làm vậy thì post chừng 65k bài viết là hết post được. sửa lại đi. để interger.
