### ISSUE TITLE
DataBase_NEWS  hoàn chỉnh .

### ISSUE THREAD

**Issue by leminhquocbt** [laravel-noobs/NEWS#35]
![DataBase for NEWS]
(https://www.dropbox.com/s/geop1l8e43h1mgy/database_NEWS.png?dl=1)

**Comment by frkami123** [comment]
post vào trong issue #2 , sao lại để vào đây?

**Comment by frkami123** [comment]
cái #2  chưa đóng mà ông mở cái này xem như là bị trùng rồi... bạn đóng lại đấy, qua bên kia mà làm.
