### ISSUE TITLE
flash messages để thông báo kết quả hành động

### ISSUE THREAD

**Issue by frkami123** [laravel-noobs/NEWS#53]
https://laracasts.com/series/laravel-5-fundamentals/episodes/20

**Comment by frkami123** [comment]
không dùng Laracast/Flash nhá. =.= tự viết một cái luôn.

**Comment by giang69** [comment]
cái này phải chỉ mới dc.

**Comment by frkami123** [comment]
cái này tui đang làm rồi.

**Comment by frkami123** [comment]
php -c php-composer.ini composer.phar update koutsuneka/flashmessage --prefer-source

dùng composer để update package  flashmessage vào thư mục vendor

**Comment by frkami123** [comment]
#57  merge trước khi hoàn thành. Lỗi sub package. composer.json
